# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-Y5hoiaDaXiU5kkdFl5X9AeDrm9QScn
"""

"""
Quantum State Optimization Under Locality Constraints

A package for optimizing quantum state transformations using local operations
and the Extreme Photon Loss (EPL) distillation protocol.
"""

__version__ = "0.1.0"
__author__ = "Your Name"

from .quantum_utils import (
    FEF,
    random_stiefel_matrix,
    transformed_rho,
    small_random_rotation_8d
)

from .distillation import EPL_distillation_protocol

from .optimization import (
    state_transformation,
    probabilistic_local_operation
)

__all__ = [
    "FEF",
    "random_stiefel_matrix",
    "transformed_rho",
    "small_random_rotation_8d",
    "EPL_distillation_protocol",
    "state_transformation",
    "probabilistic_local_operation",
]