# -*- coding: utf-8 -*-
"""constants.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-Y5hoiaDaXiU5kkdFl5X9AeDrm9QScn
"""

"""
Constants and basis matrices for quantum operations.
"""

import numpy as np

# Quantum system dimensions
QUBIT_DIM = 2
TWO_QUBIT_DIM = 4
FOUR_QUBIT_DIM = 16
STIEFEL_DIM_N = 8
STIEFEL_DIM_P = 2

# Bell state transformation unitary
U_BELL = np.matrix([
    [1,   0,   0,   1],
    [-1j, 0,   0,  1j],
    [0,  -1j, -1j,  0],
    [0,   1,  -1,   0]
]) / np.sqrt(2)

# Standard two-qubit states
PHI_PLUS = np.array([
    [0.5, 0,   0,   0.5],
    [0,   0,   0,   0],
    [0,   0,   0,   0],
    [0.5, 0,   0,   0.5]
])

# Hermitian observables for state characterization
H1 = PHI_PLUS.copy()

H2 = np.diag([0, 1, 0, 0])

H3 = np.array([
    [0, 1, 0, 0],
    [1, 0, 0, 1],
    [0, 0, 0, 0],
    [0, 1, 0, 0]
])

H4 = 1j * np.array([
    [0, -1, 0,  0],
    [1,  0, 0,  1],
    [0,  0, 0,  0],
    [0, -1, 0,  0]
])

# Basis matrices for 8x2 Stiefel manifold
def generate_basis_matrices():
    """
    Generate basis matrices for the tangent space projections.

    Returns:
        list: List of 16 basis matrices (8x2 each)
    """
    basis_matrices = []
    for i in range(STIEFEL_DIM_N):
        for j in range(STIEFEL_DIM_P):
            basis_matrix = np.zeros((STIEFEL_DIM_N, STIEFEL_DIM_P), dtype=complex)
            basis_matrix[i, j] = 1
            basis_matrices.append(basis_matrix)
    return basis_matrices

BASIS_MATRICES = generate_basis_matrices()