# -*- coding: utf-8 -*-
"""metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-Y5hoiaDaXiU5kkdFl5X9AeDrm9QScn
"""

import numpy as np
from qiskit.quantum_info import DensityMatrix


def FEF(rho):
    """
    If rho is a numpy array, it is wrapped into qiskit.quantum_info.DensityMatrix.
    """
    U = np.matrix(
        [
            [1,   0,   0,   1],
            [-1j, 0,   0,  1j],
            [0,  -1j, -1j,  0],
            [0,   1,  -1,   0],
        ],
        dtype=complex,
    ) / (2**0.5)

    if isinstance(rho, np.ndarray):
        rho = DensityMatrix(rho)

    rho_bell = rho.evolve(U)
    eigvals = np.linalg.eigvals(np.real(rho_bell.data))
    return max(np.real_if_close(eigvals))


def inner_product(A, B):
    """
    real part of Hilbert–Schmidt inner product.
    """
    return np.real(np.trace(A.conj().T @ B))


def trace_norm(A):
    """
    sqrt(<A,A>) using inner_product above.
    """
    return np.sqrt(inner_product(A, A))