# -*- coding: utf-8 -*-
"""protocols.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-Y5hoiaDaXiU5kkdFl5X9AeDrm9QScn
"""

import numpy as np
from qiskit import QuantumCircuit
from qiskit.quantum_info import DensityMatrix, Operator, partial_trace


def EPL_distillation_protocol(rho: DensityMatrix):
    """
    Entanglement distillation using a bilateral CNOT
    followed by post-selection.

    Steps:
      1) Prepare two copies rho ⊗ rho (4 qubits total).
      2) Apply the same CNOT pattern to both parties ("bilateral CNOT").
      3) Measure the *target* pair and post-select outcome "11".
      4) Trace out the measured qubits and renormalize.

    Returns:
      (rho_out, p_success)
        rho_out: 2-qubit DensityMatrix after post-selection
        p_success: probability of the selected outcome
    """
    if not isinstance(rho, DensityMatrix):
        rho = DensityMatrix(rho)

    # Bilateral CNOT unitary
    qc = QuantumCircuit(4)
    qc.cx(2, 0)
    qc.cx(3, 1)
    bilateral_cnot = Operator(qc)

    rho2 = rho.tensor(rho)  # 4-qubit state
    rho_after = rho2.evolve(bilateral_cnot)

    # Success probability for measuring qubits [0, 1] == "11"
    probs = rho_after.probabilities_dict(qargs=[0, 1])
    p_success = float(probs.get("11", 0.0))

    if p_success <= 0.0:
        # Return a valid object even if success is impossible
        return DensityMatrix(np.zeros((4, 4), dtype=complex), dims=[2, 2]), 0.0

    # Projector onto |11><11| on the selected 2-qubit subsystem
    P1 = np.array([[0, 0], [0, 1]], dtype=complex)
    Pi_11 = np.kron(P1, P1)

    # Full projector (acts on the 4-qubit system)
    I_source = np.eye(4, dtype=complex)
    Pi_full = np.kron(I_source, Pi_11)

    post = Pi_full @ rho_after.data @ Pi_full.conj().T
    rho_post = DensityMatrix(post, dims=[2, 2, 2, 2])

    # Trace out the measured qubits and renormalize
    rho_out = partial_trace(rho_post, [0, 1])
    rho_out = DensityMatrix(rho_out.data / p_success, dims=[2, 2])

    return rho_out, p_success