# -*- coding: utf-8 -*-
"""states.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-Y5hoiaDaXiU5kkdFl5X9AeDrm9QScn
"""

import numpy as np


# Bell state density matrix |Phi+><Phi+| in the computational basis
Phi = np.array(
    [
        [0.5, 0.0, 0.0, 0.5],
        [0.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 0.0],
        [0.5, 0.0, 0.0, 0.5],
    ],
    dtype=complex,
)

# Hermitian observables used in the notebook experiments
H1 = Phi
H2 = np.diag([0, 1, 0, 0]).astype(complex)

H3 = np.array(
    [
        [0, 1, 0, 0],
        [1, 0, 0, 1],
        [0, 0, 0, 0],
        [0, 1, 0, 0],
    ],
    dtype=complex,
)

H4 = 1j * np.array(
    [
        [0, -1, 0, 0],
        [1,  0, 0, 1],
        [0,  0, 0, 0],
        [0, -1, 0, 0],
    ],
    dtype=complex,
)


def S_state(p):
    """
      S_state(p) = p*Phi + (1-p)*diag([1,0,0,0])
    """
    return p * Phi + (1 - p) * np.diag([1, 0, 0, 0])


def R_state(p):
    """
      R_state(p) = p*Phi + (1-p)*H2
    """
    return p * Phi + (1 - p) * H2


def RS_state(p):
    """
      RS_state(p) = p*Phi + (1-p)*diag([1,1,0,0])/2
    """
    return p * Phi + (1 - p) * (np.diag([1, 1, 0, 0]) / 2)


def random_real_density_matrix(d=4, seed=None):
    """
    real PSD matrix normalized to trace 1.
    """
    rng = np.random.default_rng(seed)
    A = rng.normal(size=(d, d))
    R = A @ A.T  # PSD
    return R / np.trace(R)